import pygame

RESIZABLE: int = pygame.RESIZABLE
NOFRAME: int = pygame.NOFRAME
FULLSCREEN: int = pygame.FULLSCREEN
DOUBLEBUF: int = pygame.DOUBLEBUF
OPENGL: int = pygame.OPENGL
HWSURFACE: int = pygame.HWSURFACE
SWSURFACE: int = pygame.SWSURFACE
SCALED: int = pygame.SCALED
ANYFORMAT: int = pygame.ANYFORMAT
HWACCEL: int = pygame.HWACCEL
SRCALPHA: int = pygame.SRCALPHA

SYS_CURSOR_ARROW: int = pygame.SYSTEM_CURSOR_ARROW
SYS_CURSOR_IBEAM: int = pygame.SYSTEM_CURSOR_IBEAM
SYS_CURSOR_WAIT: int = pygame.SYSTEM_CURSOR_WAIT
SYS_CURSOR_CROSSHAIR: int = pygame.SYSTEM_CURSOR_CROSSHAIR
SYS_CURSOR_WAITARROW: int = pygame.SYSTEM_CURSOR_WAITARROW
SYS_CURSOR_SIZENWSE: int = pygame.SYSTEM_CURSOR_SIZENWSE
SYS_CURSOR_SIZENESW: int = pygame.SYSTEM_CURSOR_SIZENESW
SYS_CURSOR_SIZEWE: int = pygame.SYSTEM_CURSOR_SIZEWE
SYS_CURSOR_SIZENS: int = pygame.SYSTEM_CURSOR_SIZENS
SYS_CURSOR_SIZEALL: int = pygame.SYSTEM_CURSOR_SIZEALL
SYS_CURSOR_NO: int = pygame.SYSTEM_CURSOR_NO
SYS_CURSOR_HAND: int = pygame.SYSTEM_CURSOR_HAND


TOPLEFT = "topleft"
TOPRIGHT = "topright"
BOTTOMLEFT = "bottomleft"
BOTTOMRIGHT = "bottomright"
CENTER = "center"
MIDTOP = "midtop"
MIDBOTTOM = "midbottom"
MIDLEFT = "midleft"
MIDRIGHT = "midright"

MSGBOX_ERROR = 0
MSGBOX_WARNING = 10
MSGBOX_MSG = 20
MSGBOX_INFO = 40
MSGBOX_QUESTION = 30
MSGBOX_SCREENSHOT = 50



from .cam import Camera
camera = Camera(anchor="center")
uicamera = Camera(anchor="topleft")
